services:
  redis:
    image: redis:7-alpine
    container_name: city-redis
    restart: unless-stopped
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  --save 60 1000 --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - city-network

  api:
    build: .
    container_name: city-api
    restart: unless-stopped
    expose:
      - "5000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - city-network

  # runs once to populate Redis
  loader:
    build: .
    container_name: city-loader
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python app.py load
    restart: "no"
    networks:
      - city-network

volumes:
  redis_data:

# Hoping this part would fix the external connections that can be corrupting the data
networks:
  city-network:
    driver: bridge